In [2303]:
import numpy as np 
import math 

# 1. load image

In [2304]:
seven = np.array([
    [0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
], dtype=np.float32)
seven = seven[np.newaxis, :]
print(seven.shape)

(1, 28, 28)


In [2305]:
seven = np.array([
    [1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
])
seven = seven[np.newaxis, :]
print(seven.shape)

# 0 0 0 0 0 0 0 0 0
# 0 1 1 1 1 1 1 1 0
# 0 0 0 0 0 0 1 0 0
# 0 0 0 0 0 1 0 0 0
# 0 0 0 0 1 0 0 0 0
# 0 0 0 1 0 0 0 0 0
# 0 0 0 1 0 0 0 0 0
# 0 0 0 1 0 0 0 0 0
# 0 0 0 0 0 0 0 0 0

(1, 7, 7)


In [2306]:
def init_kernel(in_channels, out_channels, kernel_size):
    w = np.random.randn(
        in_channels,
        out_channels,
        kernel_size,
        kernel_size
    )
    bias = np.zeros(out_channels)
    
    #test w
    # w = np.ones((1, 8, 3, 3))
    # bias = np.zeros(8)

    return w, bias

def init_linear_w(in_channels, out_channels):
    w = np.random.rand(
            out_channels, 
            in_channels
        )
    bias = np.zeros(out_channels)
    return w, bias


In [2307]:
def convolutional(data, weigh, bias, padding=1, stride=1):
    original_size = data.shape[1]
    in_channels = weigh.shape[0]
    out_channels = weigh.shape[1]
    kernel_size = weigh.shape[2]
    
    pad_width = ((0,0), (padding, padding), (padding, padding))
    data = np.pad(data, pad_width, mode='constant', )
    
    out_size = int((original_size - kernel_size + 2 * padding) / stride + 1)

    res = np.zeros((out_channels, out_size, out_size))
    
    for feat_map_idx, feature_map in enumerate(data):
        points = np.zeros((out_size, out_size))
        Filter = weigh[:, feat_map_idx, :, :]
        for i in range(out_size):
            for j in range(out_size):
                input_patch = data[:, i:i+kernel_size, j:j+kernel_size]
                product = np.sum(input_patch * Filter) + bias[feat_map_idx]
                points[i][j] = product
        res[feat_map_idx] = points
    return res

In [2308]:
def conv2D(data, w, bias, padding=1, stride=1):
    res = convolutional(data, w, bias, padding=padding, stride=stride)
    return res

In [2309]:
def Relu(data):
    res = np.where(data > 0, data, 0)
    return res

In [2310]:
def MaxPool(data, size):
    features = data.shape[0]
    data_size = data.shape[1]
    
    out_size = int((data.shape[1] - size) / size + 1)
    res = np.zeros((features, out_size, out_size))
    
    for idx, feature_map in enumerate(data):
        submatrices = []
        for i in range(0, data_size, size):
            for j in range(0, data_size, size):
                sub_arr = np.array(feature_map[i:i+size, j:j+size])
                if sub_arr.shape[0] == size and sub_arr.shape[1] == size:
                    maxpool = np.max(sub_arr)
                    submatrices.append(maxpool)
        submatrices = np.array(submatrices)
        submatrices = submatrices.reshape(out_size, out_size)
                    
        res[idx] = submatrices
    return res   

In [2311]:
def flatten(data):
    res = []
    
    for feat in data:
        for i in range(len(feat)):
            for j in range(len(feat)):
                res.append(feat[i][j])
    return np.array(res)

In [2312]:
def Linear(data, w, bias):
    res = []
    
    for idx, feat in enumerate(w):
        tmp = data @ feat
        tmp += bias[idx]
        res.append(tmp)
    return np.array(res), data

In [2313]:
def Softmax(data):
    sum = 0
    res = []
    for vals in data:
        sum += np.exp(vals)
    for vals in data:
        res.append(np.exp(vals)/sum)
    return res
        

In [2314]:
def pick_number(p):
    res_vals = 0
    pred = 0
    for idx, vals in enumerate(p):
        if (vals > res_vals):
            pred = idx 
            res_vals = vals 
    return pred

## conv2D(data, in_channels, out_channels, kernel_size)
=> include initial kernel + convolutional 

## Relu(data)
=> Calculate relu

## MaxPool(data, size)
=> auto set padding = 0 and stride = size
```
1 2 3 4 5 1
2 1 2 3 2 1
5 6 5 2 1 1
5 6 1 2 4 1
2 3 2 3 1 1

[1 2 3] 4 5 1
[2 1 2] 3 2 1
[5 6 5] 2 1 1
  5 6 1 2 4 1
  2 3 2 3 1 1 
|
1 2 3 [4 5 1]
2 1 2 [3 2 1]
5 6 5 [2 1 1]
5 6 1 2 4 1
2 3 2 3 1 1
```

## Flatten(X)
=> flatten all tensor

## Linear
=> calculate fully connected layer

In [2315]:
def Loss(label, pred):
    loss = 0

    for i in range(len(label)):
        loss += -label[i] * np.log(pred[i])

    return loss

In [2316]:
cache = {}

W1, b1 = init_kernel(1, 8, 3)
W2, b2 = init_kernel(8, 16, 3)

W3, b3 = init_linear_w(16, 10)

def Model(inputs):
    cache["conv1_input"] = inputs
    outputs = conv2D(inputs, W1, b1)
    cache["conv1_W"] = W1
    cache["conv1_bias"] = b1
    cache["relu1_input"] = outputs
    outputs = Relu(outputs)
    cache["pool1_input"] = outputs
    outputs = MaxPool(outputs, 2)
    cache["conv2_input"] = outputs

    outputs = conv2D(outputs, W2, b2)
    cache["conv2_W"] = W2
    cache["conv2_bias"] = b2
    cache["relu2_input"] = outputs
    outputs = Relu(outputs)
    cache["pool2_input"] = outputs
    outputs = MaxPool(outputs, 2)


    cache["flatten_shape"] = outputs.shape
    outputs = flatten(outputs)

    outputs, linear_data = Linear(outputs, W3, b3)
    cache["linear_data"] = linear_data
    cache["linear_W"] = W3
    cache["linear_bias"] = b3
    
    outputs = Softmax(outputs)

    return outputs

In [2317]:
p = Model(seven)
for idx, val in enumerate(p):
    print(idx, val)

pred = pick_number(p)
print("Predict number: ", pred)

label = np.array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])
loss = Loss(label, p)
print("loss: ", loss)

0 0.0023419585674348746
1 0.018176211668007373
2 0.00044535918407404506
3 0.0007160865246955597
4 0.08198498911543002
5 0.0002553143030691619
6 0.002658553716417495
7 0.89135469450346
8 0.0018380211393413323
9 0.0002288112780701048
Predict number:  7
loss:  0.11501284486401324


In [2318]:
def Softmax_backward(pred, target):
    return pred - target

grad = Softmax_backward(p, label)

In [2319]:
def Linear_backward(grad, data, w):

    dW = np.outer(grad, data)

    db = grad.copy()

    dx = w.T @ grad

    return dx, dW, db

data = cache["linear_data"]
W = cache["linear_W"]
dx, dW, db = Linear_backward(grad, data, W)
print("dx.shape: ", dx.shape)
print("dW.shape: ", dW.shape)
print("db.shape: ", db.shape)

dx.shape:  (16,)
dW.shape:  (10, 16)
db.shape:  (10,)


In [2320]:
def flatten_backward(dx, original_shape):
    return dx.reshape(original_shape)

original_shape = cache["flatten_shape"]
dx = flatten_backward(dx, original_shape)

print(dx.shape) 

(16, 1, 1)


In [2321]:
def MaxPool_backward(dout, data, size):

    dx = np.zeros_like(data)

    C, H, W = data.shape

    out_H = H // size
    out_W = W // size

    for c in range(C):
        for i in range(out_H):
            for j in range(out_W):

                # Lấy vùng tương ứng với output
                patch = data[
                    c,
                    i*size:(i+1)*size,
                    j*size:(j+1)*size
                ]

                # Tìm vị trí max
                max_idx = np.unravel_index(
                    np.argmax(patch),
                    patch.shape
                )

                # Đưa gradient về vị trí max
                dx[
                    c,
                    i*size + max_idx[0],
                    j*size + max_idx[1]
                ] = dout[c, i, j]

    return dx

dx = MaxPool_backward(
    dx,
    cache["pool2_input"],
    2
)
print(dx.shape)


(16, 3, 3)


In [2322]:
def Relu_backward(dout, data):

    dx = dout.copy()

    dx[data <= 0] = 0

    return dx

dx = Relu_backward(dx, cache["relu2_input"])
print(dx.shape)

(16, 3, 3)


In [2323]:
def conv2D_backward(dout, data, W, bias):

    # data: (in_channels, H, W)
    in_channels, H, W_input = data.shape

    # W: (out_channels, in_channels, kernel_size, kernel_size)
    out_channels, _, kernel_size, _ = W.shape

    H_out = H - kernel_size + 1
    W_out = W_input - kernel_size + 1

    dx = np.zeros_like(data)
    dW = np.zeros_like(W)
    db = np.zeros_like(bias)

    for co in range(out_channels):

        for i in range(H_out):

            for j in range(W_out):

                db[co] += dout[co, i, j]

                for ci in range(in_channels):

                    for u in range(kernel_size):

                        for v in range(kernel_size):

                            x = data[ci, i + u, j + v]
                            w = W[co, ci, u, v]

                            dW[co, ci, u, v] += dout[co, i, j] * x

                            dx[ci, i + u, j + v] += dout[co, i, j] * w

    return dx, dW, db

In [2324]:
# print(grad.shape)
def Backward(grad):
    dx, dW, db = Linear_backward(
        grad,
        cache["linear_data"],
        cache["linear_W"]
    )
    # print(dx.shape)
    dx = flatten_backward(
        dx,
        cache["flatten_shape"]
    )
    # print(dx.shape)
    
    dx = MaxPool_backward(
        dx,
        cache["pool2_input"],
        2
    )
    # print(dx.shape)
    
    dx = Relu_backward(
        dx,
        cache["relu2_input"]
    )
    # print(dx.shape)
    
    dx, dW2, db2 = conv2D_backward(
        dx,
        cache["conv2_input"],
        cache["conv2_W"],
        cache["conv2_bias"]
    )
    # print(dx.shape)
    
    #=================================
    dx = MaxPool_backward(
        dx,
        cache["pool1_input"],
        2
    )
    # print(dx.shape)
    
    dx = Relu_backward(
        dx,
        cache["relu1_input"]
    )
    # print(dx.shape)
    
    dx, dW1, db1 = conv2D_backward(
        dx,
        cache["conv1_input"],
        cache["conv1_W"],
        cache["conv1_bias"]
    )
    # print(dx.shape)

    return dW1, db1, dW2, db2, dW, db

In [2325]:
def update(lr):
    global W1, b1, W2, b2, W3, b3
    dW1, db1, dW2, db2, dW3, db3 = Backward(grad)

    W1 -= lr * dW1
    b1 -= lr * db1

    W2 -= lr * dW2
    b2 -= lr * db2

    W3 -= lr * dW3
    b3 -= lr * db3
    
update(0.1)

print(W1, b1)
print(W2, b2)
print(W3, b3)

[[[[ 0.77883872  0.2046429  -0.89068724]
   [ 1.18553774 -0.33005316 -0.03759297]
   [-0.60614613 -1.74401946  1.51561726]]

  [[ 0.07495288  0.23639319 -0.9536749 ]
   [-0.96451965 -0.5712974  -1.33416071]
   [-1.24815483 -0.83167563  0.85533561]]

  [[-0.03451456  0.04657216 -1.48201827]
   [ 1.02339396  1.20831074  0.07693032]
   [-0.60572543  0.81518216  0.52702936]]

  [[-1.86131515  1.32107751 -0.04659403]
   [-0.19508928 -0.69665711  0.01522553]
   [ 0.4936592   0.33772452  1.06579442]]

  [[ 0.4918698  -0.33846097 -0.96669692]
   [ 1.04110315 -0.37519412 -0.81969333]
   [ 0.96068336 -0.8832076   0.40531754]]

  [[-0.36067618 -0.06242343  1.53850616]
   [-1.08330194  0.87481376 -0.17499357]
   [-1.92496319  0.93099062 -0.02483209]]

  [[ 1.443641    1.56843521  1.22160324]
   [-0.97716126 -1.15283548 -0.35975991]
   [-1.03639302 -1.46313266  0.16098981]]

  [[ 1.18748007  2.79774566 -1.53739215]
   [-0.70305047 -0.1012206  -1.04804663]
   [ 0.91210618 -0.36296093  0.27599911]]]]

In [2326]:
# 1. Forward trước khi update

test_data = np.array([
    [1, 1, 1, 1, 1, 1, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1, 0],
    [1, 1, 1, 1, 1, 0, 0]
])
test_data = test_data[np.newaxis, :]
target = np.array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

pred_before = Model(test_data)

# 2. Tính gradient
grad = pred_before - target

# 3. Update W, b
update(0.1)

# 4. Forward lại với W, b mới
pred_after = Model(test_data)

print("Before:")
for idx, val in enumerate(pred_before):
    print(idx, val)
pred_1 = pick_number(pred_before)
print("Predict number: ", pred_1)

print()

print("After:")
for idx, val in enumerate(pred_after):
    print(idx, val)
pred_2 = pick_number(pred_after)
print("Predict number: ", pred_2)

Before:
0 0.0003630521948555158
1 0.005907022830631218
2 6.798125098183239e-05
3 0.0004645957530844156
4 0.014239194281624987
5 0.00010339469415015693
6 0.0006564924968522048
7 0.9754712955122746
8 0.002584631570297218
9 0.00014233941524762189
Predict number:  7

After:
0 0.0018010139210162962
1 0.028117671651310135
2 0.0003379806567905912
3 0.0023030040328399937
4 0.06369974746658759
5 0.8837852698119208
6 0.003249588397526107
7 0.0033871809552134882
8 0.012611269767112389
9 0.0007072733396825941
Predict number:  5
