In [1823]:
import numpy as np 
import math 

# 1. load image

In [1824]:
seven = np.array([
    [0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
], dtype=np.float32)
seven = seven[np.newaxis, :]
print(seven.shape)

(1, 28, 28)


In [1825]:
seven = np.array([
    [1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
])
seven = seven[np.newaxis, :]
print(seven.shape)

# 0 0 0 0 0 0 0 0 0
# 0 1 1 1 1 1 1 1 0
# 0 0 0 0 0 0 1 0 0
# 0 0 0 0 0 1 0 0 0
# 0 0 0 0 1 0 0 0 0
# 0 0 0 1 0 0 0 0 0
# 0 0 0 1 0 0 0 0 0
# 0 0 0 1 0 0 0 0 0
# 0 0 0 0 0 0 0 0 0

(1, 7, 7)


In [1826]:
def init_kernel(in_channels, out_channels, kernel_size):
    w = np.random.randn(
        in_channels,
        out_channels,
        kernel_size,
        kernel_size
    )
    bias = np.zeros(out_channels)
    
    #test w
    # w = np.ones((1, 8, 3, 3))
    # bias = np.zeros(8)

    return w, bias

def init_linear_w(in_channels, out_channels):
    w = np.random.rand(
            out_channels, 
            in_channels
        )
    bias = np.zeros(out_channels)
    return w, bias


In [1827]:
def convolutional(data, weigh, bias, padding=1, stride=1):
    original_size = data.shape[1]
    in_channels = weigh.shape[0]
    out_channels = weigh.shape[1]
    kernel_size = weigh.shape[2]
    
    pad_width = ((0,0), (padding, padding), (padding, padding))
    data = np.pad(data, pad_width, mode='constant', )
    
    out_size = int((original_size - kernel_size + 2 * padding) / stride + 1)

    res = np.zeros((out_channels, out_size, out_size))
    
    for feat_map_idx, feature_map in enumerate(data):
        points = np.zeros((out_size, out_size))
        Filter = weigh[:, feat_map_idx, :, :]
        for i in range(out_size):
            for j in range(out_size):
                input_patch = data[:, i:i+kernel_size, j:j+kernel_size]
                product = np.sum(input_patch * Filter) + bias[feat_map_idx]
                points[i][j] = product
        res[feat_map_idx] = points
    return res

In [1828]:
def conv2D(data, w, bias, padding=1, stride=1):
    res = convolutional(data, w, bias, padding=padding, stride=stride)
    return res

In [1829]:
def Relu(data):
    res = np.where(data > 0, data, 0)
    return res

In [1830]:
def MaxPool(data, size):
    features = data.shape[0]
    data_size = data.shape[1]
    
    out_size = int((data.shape[1] - size) / size + 1)
    res = np.zeros((features, out_size, out_size))
    
    for idx, feature_map in enumerate(data):
        submatrices = []
        for i in range(0, data_size, size):
            for j in range(0, data_size, size):
                sub_arr = np.array(feature_map[i:i+size, j:j+size])
                if sub_arr.shape[0] == size and sub_arr.shape[1] == size:
                    maxpool = np.max(sub_arr)
                    submatrices.append(maxpool)
        submatrices = np.array(submatrices)
        submatrices = submatrices.reshape(out_size, out_size)
                    
        res[idx] = submatrices
    return res   

In [1831]:
def flatten(data):
    res = []
    
    for feat in data:
        for i in range(len(feat)):
            for j in range(len(feat)):
                res.append(feat[i][j])
    return np.array(res)

In [1832]:
def Linear(data, w, bias):
    res = []
    
    for idx, feat in enumerate(w):
        tmp = data @ feat
        tmp += bias[idx]
        res.append(tmp)
    return np.array(res), data

In [1833]:
def Softmax(data):
    sum = 0
    res = []
    for vals in data:
        sum += np.exp(vals)
    for vals in data:
        res.append(np.exp(vals)/sum)
    return res
        

In [1834]:
def pick_number(p):
    res_vals = 0
    pred = 0
    for idx, vals in enumerate(p):
        if (vals > res_vals):
            pred = idx 
            res_vals = vals 
    return pred

## conv2D(data, in_channels, out_channels, kernel_size)
=> include initial kernel + convolutional 

## Relu(data)
=> Calculate relu

## MaxPool(data, size)
=> auto set padding = 0 and stride = size
```
1 2 3 4 5 1
2 1 2 3 2 1
5 6 5 2 1 1
5 6 1 2 4 1
2 3 2 3 1 1

[1 2 3] 4 5 1
[2 1 2] 3 2 1
[5 6 5] 2 1 1
  5 6 1 2 4 1
  2 3 2 3 1 1 
|
1 2 3 [4 5 1]
2 1 2 [3 2 1]
5 6 5 [2 1 1]
5 6 1 2 4 1
2 3 2 3 1 1
```

## Flatten(X)
=> flatten all tensor

## Linear
=> calculate fully connected layer

In [1835]:
def Loss(label, pred):
    loss = 0

    for i in range(len(label)):
        loss += -label[i] * np.log(pred[i])

    return loss

In [1836]:
cache = {}

W1, b1 = init_kernel(1, 8, 3)
W2, b2 = init_kernel(8, 16, 3)

W3, b3 = init_linear_w(16, 10)

def Model(inputs):
    cache["conv1_input"] = inputs
    outputs = conv2D(inputs, W1, b1)
    cache["conv1_W"] = W1
    cache["conv1_bias"] = b1
    cache["relu1_input"] = outputs
    outputs = Relu(outputs)
    cache["pool1_input"] = outputs
    outputs = MaxPool(outputs, 2)
    cache["conv2_input"] = outputs

    outputs = conv2D(outputs, W2, b2)
    cache["conv2_W"] = W2
    cache["conv2_bias"] = b2
    cache["relu2_input"] = outputs
    outputs = Relu(outputs)
    cache["pool2_input"] = outputs
    outputs = MaxPool(outputs, 2)


    cache["flatten_shape"] = outputs.shape
    outputs = flatten(outputs)

    outputs, linear_data = Linear(outputs, W3, b3)
    cache["linear_data"] = linear_data
    cache["linear_W"] = W3
    cache["linear_bias"] = b3
    
    outputs = Softmax(outputs)

    return outputs

In [1837]:
p = Model(seven)
for idx, val in enumerate(p):
    print(idx, val)

pred = pick_number(p)
print("Predict number: ", pred)

label = np.array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])
loss = Loss(label, p)
print("loss: ", loss)

0 0.0016815993579157448
1 0.3792230868728374
2 0.08129775477845022
3 0.00794164543939661
4 0.0001423978993839327
5 0.07717678964600336
6 0.12001887083170236
7 0.0108942466645914
8 0.31040094491463177
9 0.011222663595087235
Predict number:  1
loss:  4.519520458034338


In [1838]:
def Softmax_backward(pred, target):
    return pred - target

grad = Softmax_backward(p, label)

In [1839]:
def Linear_backward(grad, data, w):

    dW = np.outer(grad, data)

    db = grad.copy()

    dx = w.T @ grad

    return dx, dW, db

data = cache["linear_data"]
W = cache["linear_W"]
dx, dW, db = Linear_backward(grad, data, W)
print("dx.shape: ", dx.shape)
print("dW.shape: ", dW.shape)
print("db.shape: ", db.shape)

dx.shape:  (16,)
dW.shape:  (10, 16)
db.shape:  (10,)


In [1840]:
def flatten_backward(dx, original_shape):
    return dx.reshape(original_shape)

original_shape = cache["flatten_shape"]
dx = flatten_backward(dx, original_shape)

print(dx.shape) 

(16, 1, 1)


In [1841]:
def MaxPool_backward(dout, data, size):

    dx = np.zeros_like(data)

    C, H, W = data.shape

    out_H = H // size
    out_W = W // size

    for c in range(C):
        for i in range(out_H):
            for j in range(out_W):

                # Lấy vùng tương ứng với output
                patch = data[
                    c,
                    i*size:(i+1)*size,
                    j*size:(j+1)*size
                ]

                # Tìm vị trí max
                max_idx = np.unravel_index(
                    np.argmax(patch),
                    patch.shape
                )

                # Đưa gradient về vị trí max
                dx[
                    c,
                    i*size + max_idx[0],
                    j*size + max_idx[1]
                ] = dout[c, i, j]

    return dx

dx = MaxPool_backward(
    dx,
    cache["pool2_input"],
    2
)
print(dx.shape)


(16, 3, 3)


In [1842]:
def Relu_backward(dout, data):

    dx = dout.copy()

    dx[data <= 0] = 0

    return dx

dx = Relu_backward(dx, cache["relu2_input"])
print(dx.shape)

(16, 3, 3)


In [1843]:
def conv2D_backward(dout, data, W, bias):

    # data: (in_channels, H, W)
    in_channels, H, W_input = data.shape

    # W: (out_channels, in_channels, kernel_size, kernel_size)
    out_channels, _, kernel_size, _ = W.shape

    H_out = H - kernel_size + 1
    W_out = W_input - kernel_size + 1

    dx = np.zeros_like(data)
    dW = np.zeros_like(W)
    db = np.zeros_like(bias)

    for co in range(out_channels):

        for i in range(H_out):

            for j in range(W_out):

                db[co] += dout[co, i, j]

                for ci in range(in_channels):

                    for u in range(kernel_size):

                        for v in range(kernel_size):

                            x = data[ci, i + u, j + v]
                            w = W[co, ci, u, v]

                            dW[co, ci, u, v] += dout[co, i, j] * x

                            dx[ci, i + u, j + v] += dout[co, i, j] * w

    return dx, dW, db

In [1844]:
# print(grad.shape)
def Backward(grad):
    dx, dW, db = Linear_backward(
        grad,
        cache["linear_data"],
        cache["linear_W"]
    )
    # print(dx.shape)
    dx = flatten_backward(
        dx,
        cache["flatten_shape"]
    )
    # print(dx.shape)
    
    dx = MaxPool_backward(
        dx,
        cache["pool2_input"],
        2
    )
    # print(dx.shape)
    
    dx = Relu_backward(
        dx,
        cache["relu2_input"]
    )
    # print(dx.shape)
    
    dx, dW2, db2 = conv2D_backward(
        dx,
        cache["conv2_input"],
        cache["conv2_W"],
        cache["conv2_bias"]
    )
    # print(dx.shape)
    
    #=================================
    dx = MaxPool_backward(
        dx,
        cache["pool1_input"],
        2
    )
    # print(dx.shape)
    
    dx = Relu_backward(
        dx,
        cache["relu1_input"]
    )
    # print(dx.shape)
    
    dx, dW1, db1 = conv2D_backward(
        dx,
        cache["conv1_input"],
        cache["conv1_W"],
        cache["conv1_bias"]
    )
    # print(dx.shape)

    return dW1, db1, dW2, db2, dW, db

In [1845]:
def update(lr):
    global W1, b1, W2, b2, W3, b3
    dW1, db1, dW2, db2, dW3, db3 = Backward(grad)

    W1 -= lr * dW1
    b1 -= lr * db1

    W2 -= lr * dW2
    b2 -= lr * db2

    W3 -= lr * dW3
    b3 -= lr * db3
    
update(0.1)

print(W1, b1)
print(W2, b2)
print(W3, b3)

[[[[-0.30630709  0.66732146 -1.50699451]
   [ 0.01892829 -1.08634089  2.17271568]
   [ 1.56150523  1.20943809  0.02143142]]

  [[ 1.16731178  1.55627048  1.10546864]
   [ 0.53397047  0.01599439  1.21363936]
   [ 1.11952857  0.40934132 -0.44974542]]

  [[ 0.22126531  0.80930187  0.2423843 ]
   [ 0.52244785  0.42140281 -0.17523021]
   [-0.54844479 -0.32916619 -0.06971601]]

  [[-0.78431702 -0.37031001  0.28979158]
   [ 0.89879371  1.190461    0.4943281 ]
   [ 0.13513306 -0.25310992  1.01430352]]

  [[ 0.94027999  0.38481349 -0.2183276 ]
   [ 1.07162895 -1.66257174  1.69805869]
   [-0.83521714 -0.80837417 -0.21725131]]

  [[-0.91826244  0.77934288  0.75315655]
   [ 0.13913209  0.11388205 -1.20494243]
   [ 1.79820812  0.65686467 -1.27278417]]

  [[ 1.03596386  0.46824816 -0.50352868]
   [-1.57486823  0.69451343  0.62863146]
   [-0.49715948 -0.33289977  0.32950023]]

  [[ 0.15150913 -0.43388991  0.48629581]
   [-0.12736406  0.45043022  0.43554475]
   [ 1.01857588 -0.88808262 -0.74445432]]]]

In [ ]:
# 1. Forward trước khi update

test_data = np.array([
    [1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
])
test_data = test_data[np.newaxis, :]
target = np.array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

pred_before = Model(test_data)

# 2. Tính gradient
grad = pred_before - target

# 3. Update W, b
update(0.1)

# 4. Forward lại với W, b mới
pred_after = Model(test_data)

print("Before:")
for idx, val in enumerate(pred_before):
    print(idx, val)
pred_1 = pick_number(pred_before)
print("Predict number: ", pred_1)

print("After :", pred_after)

Before: [np.float64(5.301225168911986e-05), np.float64(0.0006212997722133964), np.float64(0.0014223289056838916), np.float64(0.00023601054418138231), np.float64(4.065984818253588e-06), np.float64(0.0013941490600821718), np.float64(0.0016668222932703584), np.float64(0.9933986513981284), np.float64(0.000886928622449573), np.float64(0.0003167311674833953)]
After : [np.float64(5.065943178903119e-05), np.float64(0.000590646279911614), np.float64(0.0013416031913673775), np.float64(0.00022530252793476533), np.float64(3.9081057141931854e-06), np.float64(0.0013153463956971606), np.float64(0.0015634854160641862), np.float64(0.9937657927026482), np.float64(0.000840714141308391), np.float64(0.0003025418075651289)]
