In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, classification_report, confusion_matrix, r2_score
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor, plot_tree
from sklearn.preprocessing import StandardScaler, MinMaxScaler,LabelEncoder

In [6]:
machine_cpu = fetch_openml(name="machine_cpu", version=1)
X = machine_cpu.data
y = machine_cpu.target
feature_names = machine_cpu.feature_names

df = pd.DataFrame(X, columns=feature_names)
df["performance"] = y

print(df.shape)
print(feature_names)
print(X)
print()
print(y)

(209, 7)
['MYCT', 'MMIN', 'MMAX', 'CACH', 'CHMIN', 'CHMAX']
     MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX
0     125   256   6000   256     16    128
1      29  8000  32000    32      8     32
2      29  8000  32000    32      8     32
3      29  8000  32000    32      8     32
4      29  8000  16000    32      8     16
..    ...   ...    ...   ...    ...    ...
204   124  1000   8000     0      1      8
205    98  1000   8000    32      2      8
206   125  2000   8000     0      2     14
207   480   512   8000    32      0      0
208   480  1000   4000     0      0      0

[209 rows x 6 columns]

0      198
1      269
2      220
3      172
4      132
      ... 
204     42
205     46
206     52
207     67
208     45
Name: class, Length: 209, dtype: int64


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(167, 6) (42, 6)
(167,) (42,)


In [8]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train)

[[-0.62496685  1.55135764  0.41961313  0.17612962  0.65310303 -0.05573806]
 [-0.67735929  3.93007968  1.8983401   0.94826802  0.65310303  0.28584934]
 [-0.66239002  1.55135764  4.85579404  2.4925448   1.34891296  6.77601003]
 ...
 [-0.25073521 -0.23268388 -0.6894321  -0.40297417 -0.56456434  0.11505564]
 [-0.17588888 -0.53002414 -0.31975036 -0.20993957 -0.56456434 -0.14113492]
 [ 3.34188863 -0.67512618 -0.92048319 -0.59600877 -0.56456434 -0.69621445]]


In [9]:
dt_regressor = DecisionTreeRegressor(max_depth=5)
dt_regressor.fit(X_train, y_train)

pred = dt_regressor.predict(X_test)

mse = mean_squared_error(y_test, pred)
rmse = np.sqrt(mse)
mae = np.mean(np.abs(y_test - pred))
r2 = r2_score(y_test, pred)

print(f"MSE: {mse:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")
print(f"R2: {r2:.4f}")


MSE: 9251.2432
RMSE: 96.1834
MAE: 44.1096
R2: 0.8183
